server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer
          predicates:
            - Path=/**
        - id: product-service
          uri: lb://product
          predicates:
            - Path=/products/**
        - id: shopping-service
          uri: lb://shopping
          predicates:
            - Path=/invoices/**
  	    


  
