spring:
  application:
    name: product-service
  cloud:
    config:

      username: root
      password: s3cr3t
  #      enabled: true
  #      uri: http://localhost:8081
  config:
    import: "optional:configserver:http://localhost:8081"

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8081/eureka