spring:
  application:
    name: shopping-service
  cloud:
    config:

      username: root
      password: s3cr3t
  #      enabled: true
  #      uri: http://localhost:8081
  config:
    import: "optional:configserver:http://localhost:8081"

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
#      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/